ritter_url = 'http://10.2.4.210:8082/process'
cmu_url = 'http://10.2.4.210:8080/CMUTager/process'
mongo_url = '10.2.4.217'
gcd_dir = '/Santosh/GCD/out'
gcd_sec = '/Santosh/GCD/out_i1'
page_view = '/Santosh/TagMe/pageviews/english-pagecount'
page_sec = '/Santosh/TagMe/pageviews/sec1'
page_old = '/Santosh/TagMe/pageviews/old-english-pagecount'
page_old_sec = '/Santosh/TagMe/pageviews/old-sec'

###AWS INSTANCE#####
# ritter_url = 'http://localhost:8082/process'
# cmu_url = 'http://localhost/CMUTager/process'
# mongo_url = 'localhost'
# gcd_dir = '/mnt/my-data/Santosh/GCD/out'
# gcd_sec = '/mnt/my-data/Santosh/GCD/out_i1'
# page_view = '/mnt/my-data/pageviews/english-pagecount'
# page_sec = '/mnt/my-data/pageviews/sec1'
# page_old = '/mnt/my-data/pageviews/old-english-pagecount'
# page_old_sec = '/mnt/my-data/pageviews/old-sec'